// Header für die Devicenamen
struct DID {
	int IDNummer;
	char DevName[LN];
	char DevShortName[SN];
};


struct DID MyDevID[] = {	
	{11, "DC Brick" , "DCBR"},
	{13, "Master Brick", "MAST" },
	{14, "Servo Brick", "SERV"},
	{15, "Stepper Brick", "STEP",},
	{16, "IMU Brick", "LLER"},
	{17, "RED Brick", "REDY"},
	{18, "IMU Brick 2.0", "LLER"},
	{21, "Ambient Light Bricklet", "LLER"},
	{23, "Current12 Bricklet", "LLER"},
	{24, "Current25 Bricklet", "LLER"},
	{25, "Distance IR Bricklet", "DISR"},
	{26, "Dual Relay Bricklet", "LLER"},
	{27, "Humidity Bricklet","HUMI"},
	{28, "IO-16 Bricklet", "LLER"},
	{29, "IO-4 Bricklet", "LLER"},
	{210, "Joystick Bricklet", "LLER"},
	{211, "LCD 16x2 Bricklet", "LLER"},
	{212, "LCD 20x4 Bricklet", "LC24" },
	{213, "Linear Poti Bricklet", "POTI"}, 
	{214, "Piezo Buzzer Bricklet", "LLER"},
	{215, "Rotary Poti Bricklet", "LLER"},
	{216, "Temperature Bricklet", "LLER"},
	{217, "Temperature IR Bricklet", "TEIR"},
	{218, "Voltage Bricklet", "LLER"},
	{219, "Analog In Bricklet", "LLER"},
	{220, "Analog Out Bricklet", "LLER"},
	{221, "Barometer Bricklet", "BARO"},
	{222, "GPS Bricklet", "GPSB"},
	{223, "Industrial Digital In 4 Bricklet", "LLER"},
	{224, "Industrial Digital Out 4 Bricklet", "LLER"},
	{225, "Industrial Quad Relay Bricklet", "LLER"},
	{226, "APTC Bricklet", "LLER"},
	{227, "Voltage/Current Bricklet", "LLER"},
	{228, "Industrial Dual 0-20mA Bricklet", "LLER"},
	{229, "Distance US Bricklet", "DISU"},
	{230, "Dual Button Bricklet", "DUAL"},
	{231, "LED Strip Bricklet", "LLER"},
	{232, "Moisture Bricklet", "LLER"},
	{233, "Motion Detector Bricklet", "LLER"},
	{234, "Multi Touch Bricklet", "MULT"},
	{235, "Remote Switch Bricklet", "LLER"},
	{236, "Rotary Encoder Bricklet", "LLER"},
	{237, "Segment Display 4x7 Bricklet", "LLER"},
	{238, "Sound Intensity Bricklet", "LLER"},
	{239, "Tilt Bricklet", "LLER"},
	{240, "Hall Effect Bricklet", "LLER"},
	{241, "Line Bricklet", "LLER"},
	{242, "Piezo Speaker Bricklet", "LLER"},
	{243, "Color Bricklet", "COLB"},
	{244, "Solid State Relay Bricklet", "LLER"},
	{245, "Heart Rate Bricklet", "LLER"},
	{246, "NFC/RFID Bricklet", "LLER"},
	{249, "Industrial Dual Analog In Bricklet", "LLER"},
	{250, "Accelerometer Bricklet", "ACCL"},
	{251, "Analog In Bricklet 2.0", "LLER"},
	{252, "Gas Detector Bricklet", "LLER"},
	{253, "Load Cell Bricklet", "LLER"},
	{254, "RS232 Bricklet", "LLER"},
	{255, "Laser Range Finder Bricklet", "LASR"},
	{256, "Analog Out Bricklet 2.0", "LLER"},
	{257, "AC Current Bricklet", "LLER"},
	{258, "Industrial Analog Out Bricklet", "LLER"},
	{259, "Ambient Light Bricklet 2.0", "LLER"},
	{260, "Dust Detector Bricklet", "LLER"},
	{261, "Ozone Bricklet", "LLER"},
	{262, "CO2 Bricklet", "LLER"}
};
